#
# Copyright: (c) 2015 by Petr Zemek <s3rvac@gmail.com>
# License:   BSD, see LICENSE for more details
#

.PHONY: all clean

all:
	make -C cpp11 all
	make -C cpp14 all

clean:
	make -C cpp11 clean
	make -C cpp14 clean
